---
- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: reload httpd
  ansible.builtin.service:
    name: httpd
    state: reloaded

- name: restart nexus
  ansible.builtin.service:
    name: nexus
    state: restarted
